python3 main.py \
    --batch_size 2 \
    --num_workers 2 \
    --classifier_lr 1e-4 \
    --wav2vec2_lr 1e-5 \
    --max_epochs 10 \
    --accelerator cpu \
    --weight_decay 0.001 \
    --warmup_steps 0.1 \
    --constant_steps 0.4 \
    --scheduler_factor 0.001 \
    --data_dir data \
    --ckpt_dir ckpt
